# Generated by Django 4.0.1 on 2024-04-13 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0002_watchlist_name_remove_watchlist_stock_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='user',
            new_name='cust',
        ),
    ]
